services:
  mockoon:
    image: mockoon/cli:latest
    ports:
      - "3000:3000"
    volumes:
      - ./demo.json:/data
    command: -d /data -p 3000
  angular-ui:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "80:80"
